version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 6543:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=fuzzy
      - POSTGRES_DB=fuzzy
